/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Hellper.C_Connection;
import Hellper.Hellper_Portal;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;

/**
 *
 * @author PCIT1
 */
public class JFrame_Payment_Reprint extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Payment_Reprint
     */
    Connection connection;
    Statement stt;
    String sql;
    ResultSet res;
    PreparedStatement ps = null;
    Hellper_Portal hellper_Portal;
    public int nilai = 0;
    public String _Doc_Header;
    public String _Payment;
    public String _Change;

    public JFrame_Payment_Reprint() {
        initComponents();
    }

    public JFrame_Payment_Reprint(String Doc_Header, String Payment, String Change) {
        initComponents();
        _Doc_Header = Doc_Header;
        _Payment = Payment;
        _Change = Change;
    }

//    Doc_Header
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setText("RePrint");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("New Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(416, 116));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            sql = "DELETE FROM [192.168.12.12].[dbstore_ho].[dbo].[t_pos_log]";
            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            stt.executeUpdate(sql);
            this.setVisible(false);
            JFrame_PaymentConsigment jFrame_PaymentConsigment = new JFrame_PaymentConsigment(null,10);
            jFrame_PaymentConsigment.setVisible(true);
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        printData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void printData() {

        PrinterJob pj = PrinterJob.getPrinterJob();
        PageFormat pf = pj.defaultPage();
        Paper paper = new Paper();
        paper.setSize(220, 500);
        double margin = 10;
        paper.setImageableArea(margin, margin, paper.getWidth() - margin, paper.getHeight()
                - margin);
        pf.setPaper(paper);

        pj.setPrintable(new MyPrintable(), pf);
        if (pj.printDialog()) {
            try {
                pj.print();

            } catch (PrinterException e) {
                System.out.println(e);
            }
        }

        try {
            sql = "DELETE FROM [192.168.12.12].[dbstore_ho].[dbo].[t_pos_log]";
            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            stt.executeUpdate(sql);
            this.setVisible(false);
            JFrame_PaymentConsigment jFrame_PaymentConsigment = new JFrame_PaymentConsigment(null,10);
            jFrame_PaymentConsigment.setVisible(true);
        } catch (SQLException e) {
        }
        
    }

    class MyPrintable implements Printable {

        public int print(Graphics g, PageFormat pf, int pageIndex) {
            hellper_Portal = new Hellper_Portal();
            int count = 0;

            List<String> list;

            if (pageIndex != 0) {
                return NO_SUCH_PAGE;
            }
            Graphics2D g2 = (Graphics2D) g;
            g2.setFont(new Font("Serif", Font.PLAIN, 8));
            g2.setPaint(Color.black);
            Image image = null;
            try {

                File folderInput = new File("C:\\Users\\Logo\\logo.png");
                image = ImageIO.read(folderInput);

            } catch (IOException e) {
                e.printStackTrace();
            }

            g2.drawString("REPRINT", 90, 60);
            g2.drawImage(image, 60, 80, rootPane);

            g2.drawString("GARMELIA BAKERY", 70, 180);
            g2.drawString("STORE HO : ", 90, 190);
            g2.drawString("------------------------------------------------", 40, 200);

            try {

                System.out.println(_Doc_Header);
                sql = " SELECT * FROM [192.168.12.12].[dbstore_ho].[dbo].[t_pos_header] WHERE doc_id = '" + _Doc_Header + "'";

                connection = C_Connection.getConnection();
                stt = connection.createStatement();
                res = stt.executeQuery(sql);

                while (res.next()) {

                    g2.drawString("" + res.getString(3) + "              " + hellper_Portal.getDate() + "          " + hellper_Portal.getTime() + "", 40, 210);
                    g2.drawString("" + res.getString(1) + "", 40, 220);
                    g2.drawString("Admin               Customer              CASH", 40, 230);
                    g2.drawString("Payment : CASH", 40, 240);

                }
                res.close();
                stt.close();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }

//            g2.drawString("R006              18-11-2018          11:24:02", 40, 210);
//            g2.drawString("10000023", 40, 220);
//            g2.drawString("Admin               Customer              CASH", 40, 230);
//            g2.drawString("Payment : Debit B011414", 40, 240);
            g2.drawString("------------------------------------------------", 40, 250);

            try {

                sql = "  SELECT\n"
                        + "	A.[nomor_log_transaksi]\n"
                        + "      ,A.[material_id]\n"
                        + "      ,A.[item]\n"
                        + "      ,A.[qty]\n"
                        + "      ,A.[price]\n"
                        + "      ,A.[date]\n"
                        + "      ,A.[nik]\n"
                        + "      ,A.[amount],\n"
                        + "	   B.[material_name]\n"
                        + "  FROM \n"
                        + "  [192.168.12.12].[dbstore_ho].[dbo].[t_pos_log] AS A,\n"
                        + "  [192.168.12.12].[dbstore_ho].[dbo].[m_material] AS B\n"
                        + "  WHERE\n"
                        + "  A.material_id = B.material_id order by A.material_id desc";

                connection = C_Connection.getConnection();
                stt = connection.createStatement();
                res = stt.executeQuery(sql);
                list = new ArrayList<>();
                while (res.next()) {
                    g2.drawString("" + res.getString(9) + "             " + res.getString(8) + "", 40, 260 + ++count * 5);
                    g2.drawString("" + res.getString(4) + "x" + res.getString(5) + " ", 40, 265 + ++count * 5);
                    g2.drawString(" ", 40, 270 + ++count * 5);
                    nilai = 270 + ++count * 5;
                }

                System.out.println("nilai : " + nilai);

                res.close();
                stt.close();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }

            g2.drawString("-----------------------------------------------+", 40, 320);
            g2.drawString("TOTAL ITEM   :                                  " + hellper_Portal.TotalItems() + "", 40, 330);
            g2.drawString("TOTAL QTY    :                                  " + hellper_Portal.TotalQtys() + "", 40, 340);
            g2.drawString("TOTAL ORDER  :                       " + hellper_Portal.TotalOrders() + "", 40, 350);
            g2.drawString("DISCOUNT       :                         " + hellper_Portal.TotalDisc() + "", 40, 360);
            g2.drawString("NETTO            :                          " + hellper_Portal.TotalNett(hellper_Portal.TotalOrders(), hellper_Portal.TotalDisc()) + "", 40, 370);
            g2.drawString("=====", 150, 380);
            g2.drawString("PAYMENT      :                            " + _Payment + "", 40, 390);
            g2.drawString("PAYMENT CARD :                             0", 40, 400);
            g2.drawString("CHANGE       :                                " + _Change + "", 40, 410);
            g2.drawString("------------------------------------------------", 40, 420);
            g2.drawString("Harga Sudah Termasuk PPN", 60, 430);
            g2.drawString("TERIMA KASIH ", 70, 440);
            g2.drawString("Barang Yang Sudah DiBeli Tidak Dapat DiTukar", 20, 450);
            g2.drawString("-------------------------------------------------", 40, 460);
            g2.drawString("NPWP : 02.011.654.7-441.00", 65, 470);
            g2.drawString("www.garmeliabakery.com ", 70, 480);
            g2.drawString("Email : marketing@garmeliabakery.com ", 50, 490);

            return PAGE_EXISTS;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Payment_Reprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Payment_Reprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Payment_Reprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Payment_Reprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Payment_Reprint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
