/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Hellper.C_Connection;
import Hellper.Hellper_Portal;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.misc.BASE64Decoder;

/**
 *
 * @author PCIT1
 */
public class JFrame_HelpDesk_Detail extends javax.swing.JFrame {

    Connection connection;
    Statement stt;
    String sql;
    ResultSet res;
    PreparedStatement ps = null;
    Hellper_Portal hellper_Portal;

    /**
     * Creates new form JFrame_HelpDesk_Detail
     */
    public String _IdHelpDesk;
    public String _Nik;
    public String nomor_statuspekerjaan = null;
    public String nomor_ticket = null;
    public String nik_closed = null;
    public String status_pekerjaan = null;
    public String komentar = null;
    public String tanggal = null;

    public JFrame_HelpDesk_Detail() {
        initComponents();
    }

    public JFrame_HelpDesk_Detail(String IdHelpDesk, String Nik) {
        initComponents();
        this.hellper_Portal = new Hellper_Portal();
        _Nik = Nik;
        _IdHelpDesk = IdHelpDesk;

        ImageIcon imageIcon = new ImageIcon(decodeToImage(hellper_Portal.getImage(IdHelpDesk)));
//        txt_image.getWidth()
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(459, 120, java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(newimg);  // transform it back
        txt_image.setIcon(imageIcon);
        
        getData(_IdHelpDesk);
        getDeptType();
        getDataKompentar();
        getDataName();
        EnableAfterEdeting();
        txt_komentar.setLineWrap(true);
        txt_catatan.setLineWrap(true);
    }

    public final BufferedImage decodeToImage(String imageString) {

        BufferedImage image = null;
        byte[] imageByte;
        try {
            BASE64Decoder decoder = new BASE64Decoder();
            imageByte = decoder.decodeBuffer(imageString);
            try (ByteArrayInputStream bis = new ByteArrayInputStream(imageByte)) {
                image = ImageIO.read(bis);
                image.getScaledInstance(30, 50, 30);
            }
        } catch (IOException e) {
        }
        return image;
    }

    private void EnableAfterEdeting() {

        if (hellper_Portal.getDept(_Nik) == null) {
            jc_status.setEnabled(false);
            txt_komentar.setEnabled(false);
            jButton1.setEnabled(false);
            JC_Dept.setEnabled(false);
            JC_Users.setEnabled(false);
            txt_catatan.setEnabled(false);
            JbKirim.setEnabled(false);
        } else if (hellper_Portal.getDept(_Nik).equals("IT Department")) {
            jc_status.setEnabled(true);
            txt_komentar.setEnabled(true);
            jButton1.setEnabled(true);
            JC_Dept.setEnabled(true);
            JC_Users.setEnabled(true);
            txt_catatan.setEnabled(true);
            JbKirim.setEnabled(true);
        } else {
            if (hellper_Portal.CountClose(_IdHelpDesk) != 0) {
                jc_status.setEnabled(false);
                txt_komentar.setEnabled(false);
                jButton1.setEnabled(false);
                JC_Dept.setEnabled(false);
                JC_Users.setEnabled(false);
                txt_catatan.setEnabled(false);
                JbKirim.setEnabled(false);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jc_status = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_komentar = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Jt_Status_pekerjaan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_icon = new javax.swing.JLabel();
        txt_image = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edt_subject = new javax.swing.JTextField();
        edt_asignment = new javax.swing.JTextField();
        edt_type = new javax.swing.JTextField();
        edt_request_status = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_isipesan = new javax.swing.JTextArea();
        edt_assign_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        JC_Dept = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_catatan = new javax.swing.JTextArea();
        JbKirim = new javax.swing.JButton();
        JC_Users = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Status Pekerjaan"));

        jc_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diskusi", "closed" }));
        jc_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_statusActionPerformed(evt);
            }
        });

        txt_komentar.setColumns(20);
        txt_komentar.setRows(5);
        txt_komentar.setAutoscrolls(false);
        jScrollPane3.setViewportView(txt_komentar);

        jButton1.setText("Kirim");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Jt_Status_pekerjaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Jt_Status_pekerjaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jt_Status_pekerjaanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(Jt_Status_pekerjaan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jc_status, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jc_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Pekerjaan"));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_image, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_image, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Subject");

        jLabel2.setText("Assign Dept");

        jLabel3.setText("Request Type");

        jLabel4.setText("Request Status");

        jLabel5.setText("Isi Pesan");

        edt_subject.setEditable(false);
        edt_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_subjectActionPerformed(evt);
            }
        });

        edt_asignment.setEditable(false);
        edt_asignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_asignmentActionPerformed(evt);
            }
        });

        edt_type.setEditable(false);
        edt_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_typeActionPerformed(evt);
            }
        });

        edt_request_status.setEditable(false);
        edt_request_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_request_statusActionPerformed(evt);
            }
        });

        txt_isipesan.setEditable(false);
        txt_isipesan.setColumns(20);
        txt_isipesan.setRows(5);
        jScrollPane1.setViewportView(txt_isipesan);

        edt_assign_name.setEditable(false);
        edt_assign_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_assign_nameActionPerformed(evt);
            }
        });

        jLabel9.setText("Assign Name");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edt_subject)
                    .addComponent(edt_asignment)
                    .addComponent(edt_type)
                    .addComponent(edt_request_status)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(edt_assign_name))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edt_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_assign_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edt_asignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edt_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edt_request_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Deliver To"));

        jLabel6.setText("Dept");

        JC_Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_DeptActionPerformed(evt);
            }
        });

        jLabel7.setText("Users");

        jLabel8.setText("Catatan :");

        txt_catatan.setColumns(20);
        txt_catatan.setRows(5);
        jScrollPane2.setViewportView(txt_catatan);

        JbKirim.setText("Kirim");
        JbKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JbKirimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JbKirimMouseEntered(evt);
            }
        });
        JbKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbKirimActionPerformed(evt);
            }
        });

        JC_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_UsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JbKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JC_Dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(JC_Users, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JC_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JC_Users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(JbKirim)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edt_request_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_request_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_request_statusActionPerformed

    private void edt_asignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_asignmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_asignmentActionPerformed

    private void edt_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_typeActionPerformed

    private void JC_DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_DeptActionPerformed

    }//GEN-LAST:event_JC_DeptActionPerformed

    private void getDataName() {

        try {
            sql = "select users.name, organization.name \n"
                    + "from \n"
                    + "users JOIN profile ON profile.id = users.id join subOrganization ON subOrganization.id = profile.sub_dept \n"
                    + "JOIN organization ON organization.id = subOrganization.id_organization ";
            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                JC_Users.addItem(res.getString(1));
            }

        } catch (SQLException e) {
        }

    }

    private void edt_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_subjectActionPerformed

    private void jc_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_statusActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        try {
            if (nomor_statuspekerjaan == null) {

                sql = "INSERT INTO [dbo].[tbl_status_pekerjaan]\n"
                        + "           ([nomor_statuspekerjaan]\n"
                        + "           ,[nomor_ticket]\n"
                        + "           ,[nik_closed]\n"
                        + "           ,[status_pekerjaan]\n"
                        + "           ,[komentar]\n"
                        + "           ,[tanggal])\n"
                        + "     VALUES\n"
                        + "           ('" + hellper_Portal.ID_Pekerjaan() + "','" + _IdHelpDesk + "','" + _Nik + "','" + jc_status.getSelectedItem() + "','" + txt_komentar.getText() + "',getDate())";

                connection = C_Connection.getConnection();
                ps = connection.prepareStatement(sql);
                ps.execute();

                sql = "UPDATE [dbo].[ticket_master]\n"
                        + "   SET \n"
                        + "      [status_pengerjaan] = '" + jc_status.getSelectedItem() + "'\n"
                        + "WHERE [ticket_no] = '" + _IdHelpDesk + "'";

                stt = connection.createStatement();
                int executeUpdateMaterial = stt.executeUpdate(sql);
                if (executeUpdateMaterial >= 1) {
                    JOptionPane.showMessageDialog(null, "Terima Kasih");
                    getDataKompentar();
                    txt_komentar.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal Di Update");
                }

            } else {

                sql = "UPDATE [dbo].[tbl_status_pekerjaan]\n"
                        + "   SET \n"
                        + "      [status_pekerjaan] = '" + jc_status.getSelectedItem() + "'\n"
                        + "      ,[komentar] = '" + komentar + "'\n"
                        + "WHERE [nomor_statuspekerjaan] = '" + nomor_statuspekerjaan + "'";

                stt = connection.createStatement();
                int executeUpdateMaterial = stt.executeUpdate(sql);
                if (executeUpdateMaterial >= 1) {
                    sql = "UPDATE [dbo].[ticket_master]\n"
                            + "   SET \n"
                            + "      ,[status_pengerjaan] = '" + jc_status.getSelectedItem() + "'\n"
                            + "WHERE [ticket_no] = '" + _IdHelpDesk + "'";

                    stt = connection.createStatement();
                    int executeUpdateTicket = stt.executeUpdate(sql);
                    if (executeUpdateTicket >= 1) {
                        JOptionPane.showMessageDialog(null, "Terima Kasih");
                        getDataKompentar();
                        txt_komentar.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Gagal Di Update");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Gagal Di Update");
                }

            }

        } catch (SQLException e) {
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void JC_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_UsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JC_UsersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JbKirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbKirimMouseClicked

        String namesAssign = hellper_Portal.GetNik(JC_Users.getSelectedItem());
        try {
            sql = " UPDATE \n"
                    + "			ticket_master\n"
                    + "		   SET \n"
                    + "			asign_dept_ticket = '" + JC_Dept.getSelectedItem() + "',\n"
                    + "			asign_name_ticket = '" + namesAssign + "'\n"
                    + "		   where\n"
                    + "		    ticket_no = '" + _IdHelpDesk + "'";

            stt = connection.createStatement();
            int executeUpdate = stt.executeUpdate(sql);
            if (executeUpdate >= 1) {

                sql = "INSERT INTO [dbo].[ticket_master_delivery]\n"
                        + "           ([ticket_delivery]\n"
                        + "           ,[no_ticket]\n"
                        + "           ,[assign_dept]\n"
                        + "           ,[assign_users]\n"
                        + "           ,[assign_catatan]\n"
                        + "           ,[before_dept]\n"
                        + "           ,[before_users]\n"
                        + "           ,[before_catatan]\n"
                        + "           ,[date_delivery])\n"
                        + "     VALUES\n"
                        + "           ('" + hellper_Portal.getIDDelivery() + "','" + _IdHelpDesk + "','" + JC_Dept.getSelectedItem() + "','" + namesAssign + "','" + txt_catatan.getText() + "','" + edt_asignment.getText() + "','" + edt_assign_name.getText() + "','" + txt_isipesan.getText() + "',getDATE())";

                connection = C_Connection.getConnection();
                ps = connection.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Ticket Akan Segera Kami Kirim Ke " + JC_Users.getSelectedItem());
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Mohon Maaf Data Belum Bisa Di Update");

            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_JbKirimMouseClicked

    private void edt_assign_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_assign_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_assign_nameActionPerformed

    private void JbKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbKirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbKirimActionPerformed

    private void Jt_Status_pekerjaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jt_Status_pekerjaanMouseClicked

        int baris = Jt_Status_pekerjaan.rowAtPoint(evt.getPoint());

        nomor_statuspekerjaan = Jt_Status_pekerjaan.getValueAt(baris, 0).toString();
        status_pekerjaan = Jt_Status_pekerjaan.getValueAt(baris, 1).toString();
        komentar = Jt_Status_pekerjaan.getValueAt(baris, 2).toString();
        txt_komentar.setText(komentar);

    }//GEN-LAST:event_Jt_Status_pekerjaanMouseClicked

    private void JbKirimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbKirimMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JbKirimMouseEntered

    private void getDataKompentar() {

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Status");
        model.addColumn("Pesan");

        try {
            sql = "SELECT \n"
                    + "      [nomor_statuspekerjaan],[status_pekerjaan], [komentar]\n"
                    + "  FROM [dbo].[tbl_status_pekerjaan] WHERE nomor_ticket = '" + _IdHelpDesk + "'";

            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3)});
            }
            res.close();
            stt.close();
            Jt_Status_pekerjaan.setModel(model);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    public final void getData(String id_helpdesk) {

        try {

            sql = "SELECT [ticket_no]\n"
                    + "      ,[judul_ticket]\n"
                    + "      ,[tgl_ticket]\n"
                    + "      ,[due_date]\n"
                    + "      ,[asign_dept_ticket]\n"
                    + "      ,[asign_name_ticket]\n"
                    + "      ,[system_type]\n"
                    + "      ,[status]\n"
                    + "      ,[isi_pesan]\n"
                    + "      ,[image]\n"
                    + "      ,[nik]\n"
                    + "  FROM [dbo].[ticket_master] WHERE ticket_no = '" + _IdHelpDesk + "'";

            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                edt_subject.setText(res.getString(2));
                edt_asignment.setText(res.getString(5));
                edt_assign_name.setText(res.getString(6));
                edt_type.setText(res.getString(7));
                edt_request_status.setText(res.getString(8));
                txt_isipesan.setText(res.getString(9));
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    private void getDeptType() {
        try {
            sql = "select name from [dbo].[organization] where is_active = '1'";
            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                JC_Dept.addItem(res.getString(1).toString());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_HelpDesk_Detail.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_HelpDesk_Detail.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_HelpDesk_Detail.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_HelpDesk_Detail.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_HelpDesk_Detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JC_Dept;
    private javax.swing.JComboBox<String> JC_Users;
    private javax.swing.JButton JbKirim;
    private javax.swing.JTable Jt_Status_pekerjaan;
    private javax.swing.JTextField edt_asignment;
    private javax.swing.JTextField edt_assign_name;
    private javax.swing.JTextField edt_request_status;
    private javax.swing.JTextField edt_subject;
    private javax.swing.JTextField edt_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<String> jc_status;
    private javax.swing.JTextArea txt_catatan;
    private javax.swing.JLabel txt_icon;
    private javax.swing.JLabel txt_image;
    private javax.swing.JTextArea txt_isipesan;
    private javax.swing.JTextArea txt_komentar;
    // End of variables declaration//GEN-END:variables
}
