/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Hellper.C_Connection;
import Hellper.ReadExcel;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author PCIT1
 */
public class JFrame_AssetManagement extends javax.swing.JFrame {

    /**
     * Creates new form FormHome
     */
    Connection connection;
    Statement stt;
    String sql;
    ResultSet res;
    PreparedStatement ps = null;
    int nilaiPembanding = 0;
    int cari = 0;
    ReadExcel readExcel;
    public int Hapus = 0;

    public JFrame_AssetManagement() {
        initComponents();
        getData(cari);
        getDept();
        this.readExcel = new ReadExcel();
    }

    private void getData(int cari) {

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Asset Nomor");
        model.addColumn("Asset Nama");
        model.addColumn("CPU");
        model.addColumn("Ram");
        model.addColumn("HDD");
        model.addColumn("OS");
        model.addColumn("IP Address");
        model.addColumn("Status PC");
        model.addColumn("Computer Name");
        model.addColumn("Dept");
        model.addColumn("Location");

        try {

            if (cari == 0) {
                sql = "SELECT [asset_nomor]\n"
                        + "      ,[asset_name]\n"
                        + "      ,[cpu]\n"
                        + "      ,[ram]\n"
                        + "      ,[hdd]\n"
                        + "      ,[os]\n"
                        + "      ,[ipaddress]\n"
                        + "      ,[statuspc]\n"
                        + "      ,[computer_name]\n"
                        + "      ,[dept]\n"
                        + "      ,[location]\n"
                        + "  FROM [dbo].[tbl_assetlist]";
            } else {
                sql = "SELECT [asset_nomor]\n"
                        + "      ,[asset_name]\n"
                        + "      ,[cpu]\n"
                        + "      ,[ram]\n"
                        + "      ,[hdd]\n"
                        + "      ,[os]\n"
                        + "      ,[ipaddress]\n"
                        + "      ,[statuspc]\n"
                        + "      ,[computer_name]\n"
                        + "      ,[dept]\n"
                        + "      ,[location]\n"
                        + "  FROM [dbo].[tbl_assetlist] where asset_name = '" + edt_cari.getText() + "'";
            }

            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10), res.getString(11)});
            }

            res.close();
            stt.close();
            JTAset.setModel(model);

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    private void getDept() {

        try {
            sql = "SELECT name FROM [dbo].[organization]";
            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                JC_Dept.addItem(res.getString(1).toString());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edt_aset_nomor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edt_aset_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JC_StatusPC = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        edt_computername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JC_Dept = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAset = new javax.swing.JTable();
        edt_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edt_cpu = new javax.swing.JTextField();
        edt_ram = new javax.swing.JTextField();
        edt_hdd = new javax.swing.JTextField();
        edt_os = new javax.swing.JTextField();
        edt_ipaddress = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        edt_simpan = new javax.swing.JButton();
        edt_hapus = new javax.swing.JButton();
        edt_refresh = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        edt_location = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Asset Number");

        edt_aset_nomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_aset_nomorActionPerformed(evt);
            }
        });
        edt_aset_nomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edt_aset_nomorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edt_aset_nomorKeyTyped(evt);
            }
        });

        jLabel2.setText("Asset Name");

        edt_aset_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_aset_nameActionPerformed(evt);
            }
        });

        jLabel8.setText("Status PC");

        JC_StatusPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warning 1", "Warning 2", "Warning 3", "Critical", "Safe", " " }));

        jLabel9.setText("Computer Name");

        jLabel10.setText("Dept Nama");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edt_computername))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edt_aset_name)
                                    .addComponent(edt_aset_nomor)
                                    .addComponent(JC_StatusPC, javax.swing.GroupLayout.Alignment.TRAILING, 0, 278, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(34, 34, 34)
                                .addComponent(JC_Dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edt_aset_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edt_aset_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JC_StatusPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edt_computername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JC_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JTAset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTAset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTAsetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTAset);

        edt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_cariActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Export Excel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Import Excell");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(edt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("CPU");

        jLabel4.setText("Ram");

        jLabel5.setText("HDD");

        jLabel6.setText("OS");

        jLabel7.setText("IP Address");

        edt_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_ramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edt_cpu, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(edt_ram)
                    .addComponent(edt_hdd)
                    .addComponent(edt_os)
                    .addComponent(edt_ipaddress))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edt_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edt_ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edt_hdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edt_os, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edt_ipaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        edt_simpan.setText("Simpan");
        edt_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edt_simpanMouseClicked(evt);
            }
        });
        edt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_simpanActionPerformed(evt);
            }
        });

        edt_hapus.setText("Hapus");
        edt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_hapusActionPerformed(evt);
            }
        });

        edt_refresh.setText("Refresh");
        edt_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edt_refreshMouseClicked(evt);
            }
        });

        jLabel11.setText("Location ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edt_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edt_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edt_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edt_location)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(edt_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edt_aset_nomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_aset_nomorActionPerformed

        if (edt_aset_nomor.getText().length() <= 8) {
            JOptionPane.showMessageDialog(null, "Jumlah Digit Asset Kurang Dari 9 Karakter"); // --- Memunculkan Pesan ke User
        }

        if (CountData(edt_aset_nomor.getText()) != 0) {
            JOptionPane.showMessageDialog(null, "Data Sudah Ada");
        }
    }//GEN-LAST:event_edt_aset_nomorActionPerformed

    private int CountData(String Inputan) {
        int Hasil = 0;
        try {
            sql = "SELECT COUNT(asset_nomor) as jml FROM [dbo].[tbl_assetlist] WHERE asset_nomor = '" + Inputan + "'";

            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                Hasil = res.getInt(1);
            }

            res.close();
            stt.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return Hasil;
    }

    private void edt_aset_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_aset_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_aset_nameActionPerformed

    private void edt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_cariActionPerformed

        if (edt_cari.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Pencarian Belum Di Isi");
        } else {
            getData(1);
        }

    }//GEN-LAST:event_edt_cariActionPerformed

    private void edt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_hapusActionPerformed

        try {
            sql = "DELETE FROM [dbo].[tbl_assetlist] WHERE  asset_nomor = '" + JTAset.getValueAt(Hapus, 0).toString() + "'";
            connection = C_Connection.getConnection();
            ps = connection.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data Sudah Di Delete");
            getData(0);
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_edt_hapusActionPerformed

    private void edt_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edt_simpanMouseClicked

        if (nilaiPembanding == 0) {
            try {
                sql = "INSERT INTO [dbo].[tbl_assetlist]\n"
                        + "           ([asset_nomor]\n"
                        + "           ,[asset_name]\n"
                        + "           ,[cpu]\n"
                        + "           ,[ram]\n"
                        + "           ,[hdd]\n"
                        + "           ,[os]\n"
                        + "           ,[ipaddress]\n"
                        + "           ,[statuspc]\n"
                        + "           ,[computer_name]\n"
                        + "           ,[dept]\n"
                        + "           ,[location])\n"
                        + "     VALUES\n"
                        + "           ('" + edt_aset_nomor.getText() + "','" + edt_aset_name.getText() + "','" + edt_cpu.getText() + "','" + edt_ram.getText() + "','" + edt_hdd.getText() + "','" + edt_os.getText() + "','" + edt_ipaddress.getText() + "','" + JC_StatusPC.getSelectedItem() + "','" + edt_computername.getText() + "','" + JC_Dept.getSelectedItem() + "','" + edt_location.getText() + "')";

                connection = C_Connection.getConnection();
                ps = connection.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Terima Kasih Permintaan Akan Kami Proses");
                getData(0);
                Refresh();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {

            System.out.println(nilaiPembanding);
            try {
                sql = "UPDATE [dbo].[tbl_assetlist]\n"
                        + "   SET [asset_name] = '" + edt_aset_name.getText() + "'"
                        + "      ,[cpu] = '" + edt_cpu.getText() + "'"
                        + "      ,[ram] = '" + edt_ram.getText() + "'"
                        + "      ,[hdd] = '" + edt_hdd.getText() + "'"
                        + "      ,[os] = '" + edt_os.getText() + "'"
                        + "      ,[ipaddress] = '" + edt_ipaddress.getText() + "'"
                        + "      ,[statuspc] = '" + JC_StatusPC.getSelectedItem() + "'"
                        + "      ,[computer_name] = '" + edt_computername.getText() + "'"
                        + "      ,[dept] = '" + JC_Dept.getSelectedItem() + "'"
                        + "      ,[location] = '" + edt_location.getText() + "'"
                        + " WHERE [asset_nomor] = '" + edt_aset_nomor.getText() + "'";

                stt = connection.createStatement();
                int executeUpdate = stt.executeUpdate(sql);
                if (executeUpdate >= 1) {
                    JOptionPane.showMessageDialog(null, "Terima Kasih Data Sudah Di Update");
                    getData(0);
                    Refresh();
                } else {
                    JOptionPane.showMessageDialog(null, "Mohon Maaf Data Belum Bisa Di Update");
                    getData(0);
                    Refresh();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_edt_simpanMouseClicked

    private void edt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_simpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_simpanActionPerformed

    private void edt_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edt_refreshMouseClicked
        Refresh();
    }//GEN-LAST:event_edt_refreshMouseClicked

    private void JTAsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTAsetMouseClicked

        Hapus = JTAset.rowAtPoint(evt.getPoint());
        setDataForm(Hapus);

    }//GEN-LAST:event_JTAsetMouseClicked

    private void edt_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_ramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_ramActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        if (edt_cari.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Pencarian Belum Di Isi");
        } else {
            getData(1);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        ExportExcell();
    }//GEN-LAST:event_jButton2MouseClicked

    private void edt_aset_nomorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt_aset_nomorKeyPressed


    }//GEN-LAST:event_edt_aset_nomorKeyPressed


    private void edt_aset_nomorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt_aset_nomorKeyTyped

        if (edt_aset_nomor.getText().length() >= 10) {
            JOptionPane.showMessageDialog(null, "Jumlah Digit Asset Adalah 9 Karakter");
            evt.consume();
        }

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }


    }//GEN-LAST:event_edt_aset_nomorKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showOpenDialog(null);
            File file = jFileChooser.getSelectedFile();
            String dir = file.getAbsolutePath();
            readExcel.setInputFile(dir);
            readExcel.ngeBaca();
            getData(0);
        } catch (IOException e) {
            System.out.println("Error");
        } catch (SQLException ex) {
            Logger.getLogger(JFrame_AssetManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void setDataForm(int Nomor) {

        edt_aset_nomor.setEditable(false);
        edt_aset_nomor.setText(JTAset.getValueAt(Nomor, 0).toString());
        edt_aset_name.setText(JTAset.getValueAt(Nomor, 1).toString());
        edt_computername.setText(JTAset.getValueAt(Nomor, 8).toString());
        edt_cpu.setText(JTAset.getValueAt(Nomor, 2).toString());
        edt_ram.setText(JTAset.getValueAt(Nomor, 3).toString());
        edt_hdd.setText(JTAset.getValueAt(Nomor, 4).toString());
        edt_os.setText(JTAset.getValueAt(Nomor, 5).toString());
        edt_ipaddress.setText(JTAset.getValueAt(Nomor, 6).toString());
        edt_location.setText(JTAset.getValueAt(Nomor, 10).toString());
        edt_simpan.setText("UPDATE");
        nilaiPembanding = 1;
    }

    private void Refresh() {
        edt_aset_nomor.setEditable(true);
        edt_aset_nomor.setText("");
        edt_aset_name.setText("");
        edt_computername.setText("");
        edt_cpu.setText("");
        edt_ram.setText("");
        edt_hdd.setText("");
        edt_os.setText("");
        edt_location.setText("");
        edt_ipaddress.setText("");
        edt_simpan.setText("Simpan");
        getData(0);
        nilaiPembanding = 0;
    }

    private void ExportExcell() {

        FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("export_output/excel"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("excell file", "txt", "text");
        chooser.setFileFilter(filter);

        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {

            try {
                TableModel tModel = JTAset.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));
                for (int i = 0; i < tModel.getColumnCount(); i++) {
                    fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
                }
                fileWriter.write("\n");
                for (int i = 0; i < tModel.getRowCount(); i++) {
                    for (int j = 0; j < tModel.getColumnCount(); j++) {
                        fileWriter.write(tModel.getValueAt(i, j).toString() + "\t");
                    }
                    fileWriter.write("\n");
                }
                JOptionPane.showMessageDialog(null, "Data Sudah Di Simpan");
                fileWriter.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_AssetManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_AssetManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_AssetManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_AssetManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_AssetManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JC_Dept;
    private javax.swing.JComboBox<String> JC_StatusPC;
    private javax.swing.JTable JTAset;
    private javax.swing.JTextField edt_aset_name;
    private javax.swing.JTextField edt_aset_nomor;
    private javax.swing.JTextField edt_cari;
    private javax.swing.JTextField edt_computername;
    private javax.swing.JTextField edt_cpu;
    private javax.swing.JButton edt_hapus;
    private javax.swing.JTextField edt_hdd;
    private javax.swing.JTextField edt_ipaddress;
    private javax.swing.JTextField edt_location;
    private javax.swing.JTextField edt_os;
    private javax.swing.JTextField edt_ram;
    private javax.swing.JButton edt_refresh;
    private javax.swing.JButton edt_simpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
