/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Hellper.C_Connection;
import Hellper.Hellper_Portal;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.net.util.Base64;
import sun.misc.BASE64Decoder;

/**
 *
 * @author PCIT1
 */
public class JFrame_AddMaterial extends javax.swing.JFrame {

    Connection connection;
    Statement stt;
    String sql;
    ResultSet res;
    PreparedStatement ps = null;
    public static int statusSearching = 0;
    public int Action = 0;
    Hellper_Portal hellper_Portal;
    int baris;
    public String Doc_Nomor;
    File f;

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    /**
     * Creates new form JFrame_AddMaterial
     */
    String FileName = null;

    public JFrame_AddMaterial() {
        initComponents();
        this.hellper_Portal = new Hellper_Portal();
        MaterialGroup();
        BaseUnit();
        MaterialType();
        TableMaterial(Action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edt_material_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JC_Material_Group = new javax.swing.JComboBox<>();
        JC_MaterialType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JC_Unit = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        edt_image = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_plant = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        start_date = new datechooser.beans.DateChooserCombo();
        jLabel8 = new javax.swing.JLabel();
        enddate = new datechooser.beans.DateChooserCombo();
        jLabel9 = new javax.swing.JLabel();
        edt_harga_beli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edt_harga_jual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_image = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        edt_discount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edt_unit_conversion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        edt_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMaterial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nama Manterial");

        edt_material_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_material_nameActionPerformed(evt);
            }
        });

        jLabel2.setText("Material Group");

        JC_Material_Group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_Material_GroupActionPerformed(evt);
            }
        });

        JC_MaterialType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_MaterialTypeActionPerformed(evt);
            }
        });

        jLabel3.setText("Material Type");

        jLabel4.setText("Unit");

        JC_Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_UnitActionPerformed(evt);
            }
        });

        jLabel5.setText("Image");

        edt_image.setEditable(false);
        edt_image.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edt_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edt_imageMouseClicked(evt);
            }
        });
        edt_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_imageActionPerformed(evt);
            }
        });

        text_plant.setColumns(20);
        text_plant.setRows(5);
        jScrollPane1.setViewportView(text_plant);

        jLabel7.setText("Start Date");

        jLabel8.setText("End Date");

        jLabel9.setText("Harga Beli");

        edt_harga_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_harga_beliActionPerformed(evt);
            }
        });

        jLabel10.setText("Harga Jual");

        edt_harga_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_harga_jualActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_image.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_image, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_image, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        jLabel6.setText("Plant");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Refresh");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel11.setText("Discount");

        jLabel12.setText("Conversion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JC_MaterialType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edt_material_name)
                    .addComponent(JC_Material_Group, 0, 147, Short.MAX_VALUE)
                    .addComponent(JC_Unit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edt_unit_conversion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enddate, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(start_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1))
                            .addComponent(edt_harga_beli)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edt_harga_jual)
                            .addComponent(edt_discount))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edt_image, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(edt_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(enddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(edt_harga_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(edt_harga_jual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(edt_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_simpan)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(edt_material_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JC_Material_Group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JC_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JC_MaterialType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(edt_unit_conversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_cari.setText("CARI");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jTMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMaterialMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTMaterial);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(edt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edt_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edt_imageMouseClicked
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("*.images", "jpg", "png");
        jFileChooser.addChoosableFileFilter(extensionFilter);
        int result = jFileChooser.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            f = jFileChooser.getSelectedFile();
            edt_image.setText(f.getAbsolutePath());
            txt_image.setIcon(ResizeImage(f.getAbsolutePath(), null));
        } else {
            edt_image.setText("Tida Ada Image...");
        }
    }//GEN-LAST:event_edt_imageMouseClicked

    private void MaterialGroup() {
        try {
            sql = "SELECT materialgroup_name from [192.168.12.12].[dbstore_ho].[dbo].[m_material_group]";
            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                JC_Material_Group.addItem(res.getString(1));
            }

            res.close();
            stt.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void BaseUnit() {
        try {
            sql = "SELECT base_unit FROM [192.168.12.12].[dbstore_ho].[dbo].[m_material]  group by base_unit";
            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                JC_Unit.addItem(res.getString(1));
            }

            res.close();
            stt.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void MaterialType() {
        try {
            sql = "SELECT materialtype_name FROM [192.168.12.12].[dbstore_ho].[dbo].[m_material_type]";
            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                JC_MaterialType.addItem(res.getString(1));
            }

            res.close();
            stt.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void TableMaterial(int _statusSearching) {

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Material ID");
        model.addColumn("Material Name");
        model.addColumn("Material Group");
        model.addColumn("Start Material");
        model.addColumn("Finish Material");
        model.addColumn("Hpp");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Plant");
        model.addColumn("Image");

        try {

            if (_statusSearching == 0) {
                sql = "SELECT \n"
                        + "A.material_id, A.material_name, B.materialgroup_name, C.start_date, C.finish_date, C.hpp, C.harga_beli, C.harga_jual, A.plant, A.image\n"
                        + "FROM \n"
                        + "[192.168.12.12].[dbstore_ho].[dbo].[m_material] AS A LEFT JOIN [192.168.12.12].[dbstore_ho].[dbo].[m_material_group] AS B\n"
                        + "ON A.materialgroup_id = B.materialgroup_id LEFT JOIN [192.168.12.12].[dbstore_ho].[dbo].[m_material_price] AS C \n"
                        + "ON A.material_id = C.material_id";
            } else {
                sql = "SELECT \n"
                        + "A.material_id, A.material_name, B.materialgroup_name, C.start_date, C.finish_date, C.hpp, C.harga_beli, C.harga_jual, A.plant, A.image\n"
                        + "FROM \n"
                        + "[192.168.12.12].[dbstore_ho].[dbo].[m_material] AS A LEFT JOIN [192.168.12.12].[dbstore_ho].[dbo].[m_material_group] AS B\n"
                        + "ON A.materialgroup_id = B.materialgroup_id LEFT JOIN [192.168.12.12].[dbstore_ho].[dbo].[m_material_price] AS C \n"
                        + "ON A.material_id = C.material_id WHERE A.material_name = '" + edt_cari.getText() + "'";
            }

            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
            }
            res.close();
            stt.close();
            jTMaterial.setModel(model);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    private void TableUpdateMaterial(int setUpdate) {
        try {

            sql = "SELECT \n"
                    + "A.material_id, A.material_name, B.materialgroup_name, C.start_date, C.finish_date, C.hpp, C.harga_beli, C.harga_jual, A.plant, A.image\n"
                    + "FROM \n"
                    + "[192.168.12.12].[dbstore_ho].[dbo].[m_material] AS A LEFT JOIN [192.168.12.12].[dbstore_ho].[dbo].[m_material_group] AS B\n"
                    + "ON A.materialgroup_id = B.materialgroup_id LEFT JOIN [192.168.12.12].[dbstore_ho].[dbo].[m_material_price] AS C \n"
                    + "ON A.material_id = C.material_id WHERE A.material_id = '" + (jTMaterial.getValueAt(setUpdate, 0).toString()) + "'";

            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);
            while (res.next()) {
                edt_material_name.setText(res.getString(2));
                edt_harga_beli.setText(res.getString(7));
                edt_harga_jual.setText(res.getString(8));
                text_plant.setText(res.getString(9));
                Action = 1;
                btn_simpan.setText("Update");
            }
            res.close();
            stt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private ImageIcon Decoder(String imageString) {
        ImageIcon icon = null;
        try {
            byte[] imageByte = Base64.decodeBase64(imageString);
            ByteArrayInputStream inputStream = new ByteArrayInputStream(imageByte);
            BufferedImage bufImage = ImageIO.read(inputStream);
            icon = new ImageIcon(bufImage);
        } catch (Exception e) {
            e.printStackTrace();
        }

        return icon;
    }

    public static BufferedImage decodeToImage(String imageString) {

        BufferedImage image = null;
        byte[] imageByte;
        try {
            BASE64Decoder decoder = new BASE64Decoder();
            imageByte = decoder.decodeBuffer(imageString);
            ByteArrayInputStream bis = new ByteArrayInputStream(imageByte);
            image = ImageIO.read(bis);
            bis.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return image;
    }

    private void edt_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_imageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_imageActionPerformed

    private void edt_harga_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_harga_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_harga_beliActionPerformed

    private void edt_harga_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_harga_jualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_harga_jualActionPerformed

    private void JC_MaterialTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_MaterialTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JC_MaterialTypeActionPerformed

    private void JC_UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JC_UnitActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        if (edt_cari.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Anda Belum Mengisi Field Cari");
            TableMaterial(Action);
        } else {
            TableMaterial(1);
        }

    }//GEN-LAST:event_btn_cariActionPerformed

    private void jTMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMaterialMouseClicked
        baris = jTMaterial.rowAtPoint(evt.getPoint());
        TableUpdateMaterial(baris);
        Doc_Nomor = (jTMaterial.getValueAt(baris, 0).toString());
    }//GEN-LAST:event_jTMaterialMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed

        if (Doc_Nomor == null) {

            try {
                
                String NewMaterial = hellper_Portal.IDMaterial();
                sql = "INSERT INTO [192.168.12.12].[dbstore].[dbo].[m_material]\n"
                        + "           ([material_id]\n"
                        + "           ,[material_name]\n"
                        + "           ,[materialtype_id]\n"
                        + "           ,[materialgroup_id]\n"
                        + "           ,[materialdisplay_id]\n"
                        + "           ,[base_unit]\n"
                        + "           ,[flag_display_pos]\n"
                        + "           ,[displaygroup_id]\n"
                        + "           ,[account_id]\n"
                        + "           ,[costcenter_id]\n"
                        + "           ,[image]\n"
                        + "           ,[user_entry]\n"
                        + "           ,[user_update]\n"
                        + "           ,[create_date]\n"
                        + "           ,[modify_date]\n"
                        + "           ,[flag_active]\n"
                        + "           ,[gambar]\n"
                        + "           ,[flag_konsinyasi]\n"
                        + "           ,[old_material_id]\n"
                        + "           ,[old_material_name]\n"
                        + "           ,[plant])\n"
                        + "     VALUES\n"
                        + "           ('" + hellper_Portal.IDMaterial() + "','" + edt_material_name.getText() + "',"
                        + "'FG','" + hellper_Portal.IdMaterialGroupID(JC_Material_Group.getSelectedItem().toString()) + "',"
                        + "NULL,'" + JC_Unit.getSelectedItem() + "','Y','" + edt_material_name.getText() + "','11300100','R000'"
                        + ",'data:image/png;base64," + encodeFileToBase64Binary(f) + "','ADMIN','ADMIN',GETDATE(),GETDATE(),'Y',NULL,'N',NULL,NULL,'" + text_plant.getText() + "')";
                System.out.println(sql);
                connection = C_Connection.getConnection();
                ps = connection.prepareStatement(sql);
                ps.execute();

                sql = "INSERT INTO [192.168.12.12].[dbstore].[dbo].[m_material_price]\n"
                        + "           ([material_id]\n"
                        + "           ,[start_date]\n"
                        + "           ,[finish_date]\n"
                        + "           ,[hpp]\n"
                        + "           ,[harga_jual]\n"
                        + "           ,[disc]\n"
                        + "           ,[harga_disc]\n"
                        + "           ,[flag_active]\n"
                        + "           ,[user_entry]\n"
                        + "           ,[user_update]\n"
                        + "           ,[create_date]\n"
                        + "           ,[modify_date]\n"
                        + "           ,[harga_beli]\n"
                        + "           ,[harga_mav]\n"
                        + "           ,[unit_beli]\n"
                        + "           ,[unit_mav]\n"
                        + "           ,[flag_harga])\n"
                        + "     VALUES\n"
                        + "           ('" + NewMaterial + "','" + sdf.format(start_date.getSelectedDate().getTime()) + "','" + sdf.format(enddate.getSelectedDate().getTime()) + "',0," + edt_harga_jual.getText() + "," + edt_discount.getText() + ",NULL,'Y','ADMIN','ADMIN', GETDATE(), GETDATE(), " + edt_harga_beli.getText() + ",NULL,NULL,NULL,'B')";
                System.out.println(sql);
                connection = C_Connection.getConnection();
                ps = connection.prepareStatement(sql);
                ps.execute();

                sql = "INSERT INTO [192.168.12.12].[dbstore].[dbo].[m_slocmaterial]\n"
                        + "           ([material_id]\n"
                        + "           ,[plant_id]\n"
                        + "           ,[sloc_id]\n"
                        + "           ,[flag]\n"
                        + "           ,[user_entry]\n"
                        + "           ,[user_update]\n"
                        + "           ,[create_date]\n"
                        + "           ,[modify_date])\n"
                        + "\n"
                        + "	SELECT '" + NewMaterial + "'\n"
                        + "           ,[plant_id]\n"
                        + "           ,[sloc_id]\n"
                        + "           ,[flag]\n"
                        + "           ,[user_entry]\n"
                        + "           ,[user_update]\n"
                        + "           ,[create_date]\n"
                        + "           ,[modify_date]  FROM [192.168.12.12].[dbstore].[dbo].m_slocmaterial WHERE material_id = 'FG00284'";
                System.out.println(sql);
                connection = C_Connection.getConnection();
                ps = connection.prepareStatement(sql);
                ps.execute();

                sql = "INSERT INTO [192.168.12.12].[dbstore].[dbo].[m_unit_conversion]\n"
                        + "           ([material_id]\n"
                        + "           ,[base_unit]\n"
                        + "           ,[base_conversion]\n"
                        + "           ,[unit_conversion]\n"
                        + "           ,[X_conversion]\n"
                        + "           ,[Y_conversion]\n"
                        + "           ,[value_conversion]\n"
                        + "           ,[flag]\n"
                        + "           ,[user_entry]\n"
                        + "           ,[user_update]\n"
                        + "           ,[create_date]\n"
                        + "           ,[modify_date])\n"
                        + "     VALUES\n"
                        + "           ('" + NewMaterial + "','" + JC_Unit.getSelectedItem() + "',"
                        + "" + edt_unit_conversion.getText() + ","
                        + "'" + JC_Unit.getSelectedItem() + "',"
                        + "" + edt_unit_conversion.getText() + ","
                        + "" + edt_unit_conversion.getText() + ","
                        + "" + edt_unit_conversion.getText() + ","
                        + "'Y','ADMIN','ADMIN',GETDATE(),GETDATE())";
                System.out.println(sql);
                connection = C_Connection.getConnection();
                ps = connection.prepareStatement(sql);
                ps.execute();

                sql = "INSERT INTO [192.168.12.12].[dbstore].[dbo].[m_recipe]\n"
                        + "           ([materialdisplay_id]\n"
                        + "           ,[materialrecipe_id]\n"
                        + "           ,[qty_display]\n"
                        + "           ,[unit_display]\n"
                        + "           ,[qty_recipe]\n"
                        + "           ,[unit_recipe]\n"
                        + "           ,[qty_recipe_conv]\n"
                        + "           ,[unit_recipe_conv]\n"
                        + "           ,[flag_stock]\n"
                        + "           ,[flag_detail]\n"
                        + "           ,[flag_active]\n"
                        + "           ,[user_entry]\n"
                        + "           ,[user_update]\n"
                        + "           ,[create_date]\n"
                        + "           ,[modify_date])\n"
                        + "     VALUES\n"
                        + "           ('" + NewMaterial + "','" + NewMaterial + "',1, '" + JC_Unit.getSelectedItem() + "',1"
                        + ",'" + JC_Unit.getSelectedItem() + "',1.00,"
                        + "'" + JC_Unit.getSelectedItem() + "','Y','N','Y','ADMIN','ADMIN',GETDATE(),GETDATE())";

                connection = C_Connection.getConnection();
                ps = connection.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Proses Masukan Material Sukses, System Akan Syncronus dengan database lainya.");

            } catch (SQLException E) {
                E.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Input");
//            JOptionPane.showMessageDialog(null, "data:image/png;base64," + encodeFileToBase64Binary(f));
//            try {
//                sql = "UPDATE [192.168.12.12].[dbstore_ho].[dbo].[m_material] SET "
//                        + " m_material ='" + edt_material_name.getText() + "', "
//                        + " materialtype_id ='" + JC_MaterialType.getSelectedItem() + "', "
//                        + "materialgroup_id = '" + JC_Material_Group.getSelectedItem() + "',"
//                        + "base_unit ='" + JC_Unit.getSelectedItem() + "', "
//                        + "displaygroup_id ='" + JC_Material_Group.getSelectedItem() + "', "
//                        + "user_update ='Admin', "
//                        + "modify_date = GETDATE(), "
//                        + "image = 'data:image/png;base64," + encodeFileToBase64Binary(f) + "'"
//                        + "plant_id = '" + text_plant.getText() + "'"
//                        + "WHERE material_id = '" + Doc_Nomor + "'";
//
//                stt = connection.createStatement();
//                int executeUpdateMaterial = stt.executeUpdate(sql);
//                if (executeUpdateMaterial >= 1) {
//
//                    sql = "UPDATE [192.168.12.12].[dbstore_ho].[dbo].[m_material_price] SET "
//                            + "start_date ='" + start_date.getSelectedDate() + "', "
//                            + "finish_date ='" + enddate.getSelectedDate() + "', "
//                            + "hpp = '" + JC_Material_Group.getSelectedItem() + "',"
//                            + "harga_jual ='" + edt_harga_jual.getText() + "', "
//                            + "harga_beli ='" + edt_harga_beli.getText() + "', "
//                            + "user_update ='Admin', "
//                            + "modify_date = GETDATE() "
//                            + "WHERE material_id = '" + Doc_Nomor + "'";
//
//                    stt = connection.createStatement();
//                    int executeUpdatePrice = stt.executeUpdate(sql);
//
//                    if (executeUpdatePrice >= 1) {
//                        JOptionPane.showMessageDialog(null, " Update Berhasil");
//                    }
//                }
//
//            } catch (SQLException e) {
//                e.printStackTrace();
//            }
        }


    }//GEN-LAST:event_btn_simpanActionPerformed

    private static String encodeFileToBase64Binary(File file) {
        String Hasil = null;

        try {
            FileInputStream fileInputStreamReader = new FileInputStream(file);
            byte[] bytes = new byte[(int) file.length()];
            fileInputStreamReader.read(bytes);
            Hasil = new String(Base64.encodeBase64(bytes), "UTF-8");
        } catch (Exception e) {
            e.printStackTrace();
        }

        return Hasil;
    }

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Refresh();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        try {
            sql = "DELETE FROM [192.168.12.12].[dbstore_ho].[dbo].[t_takeorder_user] WHERE nama_cust='" + (jTMaterial.getValueAt(baris, 0).toString()) + "'";
            connection = C_Connection.getConnection();
            ps = connection.prepareStatement(sql);
            ps.execute();

            JOptionPane.showMessageDialog(this, "Terima Kasih Data Berhasil Di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        Refresh();
    }//GEN-LAST:event_jButton2MouseClicked

    private void edt_material_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_material_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_material_nameActionPerformed

    private void JC_Material_GroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_Material_GroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JC_Material_GroupActionPerformed

    private void Refresh() {
        edt_material_name.setText("");
        edt_harga_beli.setText("");
        edt_harga_jual.setText("");
        text_plant.setText("");
        edt_image.setText("");
        txt_image.setIcon(null);
        btn_simpan.setText("Simpan");
        Doc_Nomor = null;
        TableMaterial(0);

    }

    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon myImage = null;
        if (ImagePath != null) {
            myImage = new ImageIcon(ImagePath);
        } else {
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(txt_image.getWidth(), txt_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_AddMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JC_MaterialType;
    private javax.swing.JComboBox<String> JC_Material_Group;
    private javax.swing.JComboBox<String> JC_Unit;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JTextField edt_cari;
    private javax.swing.JTextField edt_discount;
    private javax.swing.JTextField edt_harga_beli;
    private javax.swing.JTextField edt_harga_jual;
    private javax.swing.JTextField edt_image;
    private javax.swing.JTextField edt_material_name;
    private javax.swing.JTextField edt_unit_conversion;
    private datechooser.beans.DateChooserCombo enddate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTMaterial;
    private datechooser.beans.DateChooserCombo start_date;
    private javax.swing.JTextArea text_plant;
    private javax.swing.JLabel txt_image;
    // End of variables declaration//GEN-END:variables
}
