/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Hellper.C_Connection;
import Hellper.Hellper_Portal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PCIT1
 */
public class JFrame_Address extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Address
     */
    Connection connection;
    Statement stt;
    String sql;
    ResultSet res;
    PreparedStatement ps = null;
    public static int statusSearching = 0;
    public int Action = 0;
    Hellper_Portal hellper_Portal;
    int baris;

    public JFrame_Address() {
        initComponents();
        getUser(statusSearching);
    }

    private void getUser(int _statusSearching) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Telp");

        try {

            if (_statusSearching == 0) {
                sql = "SELECT nama_cust, alamat, telp FROM [192.168.12.12].[dbstore_ho].[dbo].[t_takeorder_user]";
            } else {
                sql = "SELECT nama_cust, alamat, telp FROM [192.168.12.12].[dbstore_ho].[dbo].[t_takeorder_user] WHERE nama_cust ='" + edt_cari.getText() + "'";
            }

            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3)});
            }
            res.close();
            stt.close();
            tbl_user.setModel(model);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edt_nama = new javax.swing.JTextField();
        edt_alamat = new javax.swing.JTextField();
        edt_tlp = new javax.swing.JTextField();
        btn_action = new javax.swing.JButton();
        edt_hapus = new javax.swing.JButton();
        edt_hapus1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable();
        edt_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        jLabel3.setText("Telp");

        edt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_namaActionPerformed(evt);
            }
        });

        edt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_alamatActionPerformed(evt);
            }
        });

        btn_action.setText("Simpan");
        btn_action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actionActionPerformed(evt);
            }
        });

        edt_hapus.setText("Hapus");
        edt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_hapusActionPerformed(evt);
            }
        });

        edt_hapus1.setText("Refresh");
        edt_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_hapus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edt_nama)
                    .addComponent(edt_alamat)
                    .addComponent(edt_tlp, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_action, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edt_hapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(edt_hapus1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(edt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(edt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edt_hapus)))
                    .addComponent(btn_action))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edt_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_hapus1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_user);

        jButton1.setText("CARI");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(edt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        if (edt_cari.getText().isEmpty()) {
            getUser(statusSearching);
        } else {
            getUser(1);
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void edt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_namaActionPerformed

    private void edt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_alamatActionPerformed

    private void edt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_hapusActionPerformed

        try {
            sql = "DELETE FROM [192.168.12.12].[dbstore_ho].[dbo].[t_takeorder_user] WHERE nama_cust='" + (tbl_user.getValueAt(baris, 0).toString()) + "'";
            connection = C_Connection.getConnection();
            ps = connection.prepareStatement(sql);
            ps.execute();
            
            JOptionPane.showMessageDialog(this, "Terima Kasih Data Berhasil Di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
         Refresh();

    }//GEN-LAST:event_edt_hapusActionPerformed

    private void edt_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_hapus1ActionPerformed

        Refresh();
    }//GEN-LAST:event_edt_hapus1ActionPerformed

    private void Refresh(){
         edt_nama.setText("");
        edt_alamat.setText("");
        edt_tlp.setText("");
        edt_cari.setText("");
        Action = 0;
        btn_action.setText("Simpan");
        getUser(statusSearching);
    }
    private void btn_actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actionActionPerformed
        // TODO add your handling code here:
        hellper_Portal = new Hellper_Portal();
        if (edt_nama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field Nama Kosong");
        } else if (edt_alamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field Alamat Kosong");
        } else if (edt_tlp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field Tlp Kosong");
        } else {

            if (hellper_Portal.CheckAddressUser(edt_nama.getText()) > 1) {
                JOptionPane.showMessageDialog(null, "Mohon Maaf Data Sudah Ada, Silahkan Pilih Nama Lain");
            } else {
                Action(Action);
            }
        }
    }//GEN-LAST:event_btn_actionActionPerformed

    private void tbl_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_userMouseClicked

        baris = tbl_user.rowAtPoint(evt.getPoint());
        UpdateAction(baris);
    }//GEN-LAST:event_tbl_userMouseClicked

    private void UpdateAction(int setUpdate) {

        try {
            sql = "SELECT nama_cust, alamat, telp FROM [192.168.12.12].[dbstore_ho].[dbo].[t_takeorder_user] WHERE nama_cust = '" + (tbl_user.getValueAt(setUpdate, 0).toString()) + "'";
            connection = C_Connection.getConnection();
            stt = connection.createStatement();
            res = stt.executeQuery(sql);

            while (res.next()) {
                edt_nama.setText(res.getString(1));
                edt_alamat.setText(res.getString(2));
                edt_tlp.setText(res.getString(3));
                Action = 1;
                btn_action.setText("Update");
            }
            res.close();
            stt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private int Action(int baris) {
        int Hasil = 0;
        if (baris == 0) {
            try {
                sql = "INSERT INTO [192.168.12.12].[dbstore_ho].[dbo].[t_takeorder_user] \n"
                        + "(nama_cust, alamat, telp)\n"
                        + "VALUES ('" + edt_nama.getText() + "','" + edt_alamat.getText() + "','" + edt_tlp.getText() + "')";

                connection = C_Connection.getConnection();
                ps = connection.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Terima Kasih Data Sudah Di Simpan");
                getUser(statusSearching);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            try {
                sql = "UPDATE [192.168.12.12].[dbstore_ho].[dbo].[t_takeorder_user] SET nama_cust = '" + edt_nama.getText() + "', alamat = '" + edt_alamat.getText() + "' telp = '" + edt_tlp.getText() + "' where nama = '" + edt_nama.getText() + "'";

                stt = connection.createStatement();
                int executeUpdate = stt.executeUpdate(sql);
                if (executeUpdate >= 1) {
                    JOptionPane.showMessageDialog(null, "Terima Kasih Update Berhasil");
                } else {
                    JOptionPane.showMessageDialog(null, "Mohon Maaf Update Gagal");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return Hasil;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Address().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_action;
    private javax.swing.JTextField edt_alamat;
    private javax.swing.JTextField edt_cari;
    private javax.swing.JButton edt_hapus;
    private javax.swing.JButton edt_hapus1;
    private javax.swing.JTextField edt_nama;
    private javax.swing.JTextField edt_tlp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_user;
    // End of variables declaration//GEN-END:variables
}
